# This file defines charm config options, and populates the Configure tab on Charmhub.
# If your charm does not require configuration options, delete this file entirely.
#
# See https://juju.is/docs/config for guidance.

options:
  contract_url:
    default: "https://contracts.canonical.com"
    description: URL of the Ubuntu Pro contracts service backend to use.
    type: string
  ppa:
    default: ""
    description: PPA from which to install the ubuntu-advantage-tools package.
    type: string
  token:
    default: ""
    description: Ubuntu Pro token obtained from https://ubuntu.com/pro.
    type: string
  override-http-proxy:
    default: ""
    description: http-proxy which can override juju http-proxy
    type: string
  override-https-proxy:
    default: ""
    description: https-proxy which can override juju https-proxy
    type: string
  livepatch_server:
    default: ""
    description: URL of the livepatch on-prem server.
    type: string
  livepatch_token:
    default: ""
    description: Authorization token for the livepatch on-prem server.
    type: string
  services:
    default: ""
    description: Comma-separated list of services required to be activated when attaching to pro.
    type: string
