options:
  ppa:
    default: ""
    description: PPA from which to install the ubuntu-advantage-tools package
    type: string
  token:
    default: ""
    description: Ubuntu Advantage subscription token obtained from https://ubuntu.com/advantage
    type: string
  contract_url:
    default: ""
    description: Contract service url to use. Will default to the standard one if not supplied.
    type: string
