options:
  ppa:
    default: "ppa:ua-client/stable"
    description: PPA from which to install the ubuntu-advantage-tools package
    type: string
  token:
    default: ""
    description: Ubuntu Advantage subscription token obtained from https://ubuntu.com/advantage
    type: string
