options:
  contract_url:
    default: "https://contracts.canonical.com"
    description: Contract service URL to use
    type: string
  ppa:
    default: "ppa:ua-client/stable"
    description: PPA from which to install the ubuntu-advantage-tools package
    type: string
  token:
    default: ""
    description: Ubuntu Advantage subscription token obtained from https://ubuntu.com/advantage
    type: string
